disabled_rules: # rule identifiers to exclude from running
  - todo
  - force_cast
  - statement_position
  - cyclomatic_complexity
  - trailing_whitespace
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example
  - RapidTests
# parameterized rules can be customized from this configuration file
line_length:
  - 1000 # warning
  - 9999 # error
type_body_length:
  - 1000 # warning
  - 99999 # error
function_body_length:
  - 300 # warning
  - 99999 # error
file_length:
  - 2000 # warning
  - 99999 # error
variable_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
cyclomatic_complexity:
  - 30
  - 40
large_tuple:
  - 3
  - 5
generic_type_name:
  min_length:
    warning: 1
  max_length:
    warning: 30
function_parameter_count:
  - 8
  - 12
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
